const DB_NAME='hashi-db'; const DB_VERSION=1; let db; let lastCreatedId=null;
const PRIMARY=['Nausea','Stomach Ache','Brain Fog','Low Energy','Mood Swing','Bloating'];
const MORE=['Headache','Diarrhea','Constipation','Reflux','Energy Crash'];
const TRIGGERS=['Possible Gluten','Lactose','Sugar','Alcohol','Other'];
const VITAMINS=['Selenium','Vitamin D','Vitamin B'];
const CHECKIN={Overall:['Good','Okay','Rough'],Energy:['Good','Low'],Brain:['Clear','Foggy'],Stomach:['Good','Off']};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const todayKey=()=>new Date().toISOString().slice(0,10);
const fmtTime=iso=>new Date(iso).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});
const fmtDate=iso=>new Date(iso+'T12:00:00').toLocaleDateString([], {weekday:'long',month:'long',day:'numeric'});
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('events')){const s=d.createObjectStore('events',{keyPath:'id'});s.createIndex('day','day');} if(!d.objectStoreNames.contains('daily'))d.createObjectStore('daily',{keyPath:'day'});};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error);});}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function reqPromise(r){return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function addEvent(type,value){const ev={id:crypto.randomUUID(),type,value,createdAt:new Date().toISOString(),day:todayKey()};await reqPromise(tx('events','readwrite').add(ev));lastCreatedId=ev.id;showToast(`${value} logged`,true);await refreshToday();}
async function deleteEvent(id){await reqPromise(tx('events','readwrite').delete(id));await refreshToday();}
async function getAllEvents(){return await reqPromise(tx('events').getAll())}
async function getDayEvents(day){return await reqPromise(tx('events').index('day').getAll(day))}
async function getDaily(day=todayKey()){return (await reqPromise(tx('daily').get(day)))||{day,vitamins:{},period:false,checkin:{}}}
async function saveDaily(d){await reqPromise(tx('daily','readwrite').put(d))}
function chip(label,type){const b=document.createElement('button');b.className='chip action';b.textContent=label;b.dataset.eventType=type;b.dataset.eventValue=label;b.onclick=()=>addEvent(type,label);return b}
function renderButtons(){PRIMARY.forEach(x=>$('#primarySymptoms').append(chip(x,'symptom')));MORE.forEach(x=>$('#moreSymptoms').append(chip(x,'symptom')));TRIGGERS.forEach(x=>$('#triggers').append(chip(x,'trigger')));VITAMINS.forEach(x=>{const b=document.createElement('button');b.className='chip toggle';b.dataset.vitamin=x;b.textContent=x;b.onclick=()=>toggleVitamin(x);$('#vitamins').append(b)});}
async function toggleVitamin(v){const d=await getDaily();d.vitamins[v]=!d.vitamins[v];await saveDaily(d);showToast(d.vitamins[v]?`${v} marked taken`:`${v} unmarked`,false);await refreshToday();}
async function takeAll(){const d=await getDaily();VITAMINS.forEach(v=>d.vitamins[v]=true);await saveDaily(d);showToast('All vitamins marked taken',false);await refreshToday();}
async function togglePeriod(){const d=await getDaily();d.period=!d.period;await saveDaily(d);showToast(d.period?'Period marked for today':'Period unmarked',false);await refreshToday();}
function renderCheckin(){const root=$('#checkinForm');Object.entries(CHECKIN).forEach(([k,vals])=>{const row=document.createElement('div');row.className='checkin-row';row.innerHTML=`<label>${k}</label>`;const seg=document.createElement('div');seg.className='segmented '+(vals.length===2?'two':'');vals.forEach(v=>{const b=document.createElement('button');b.textContent=v;b.dataset.checkinKey=k;b.dataset.checkinValue=v;b.onclick=()=>setCheckin(k,v);seg.append(b)});row.append(seg);root.append(row)});}
async function setCheckin(k,v){const d=await getDaily();d.checkin[k]=v;await saveDaily(d);$('#checkinSaved').textContent='Saved';setTimeout(()=>$('#checkinSaved').textContent='',1200);await refreshToday();}
async function refreshToday(){const [events,d]=await Promise.all([getDayEvents(todayKey()),getDaily()]);$$('[data-vitamin]').forEach(b=>b.classList.toggle('checked',!!d.vitamins[b.dataset.vitamin]));$('#periodBtn').classList.toggle('checked',!!d.period);$$('[data-checkin-key]').forEach(b=>b.classList.toggle('selected',d.checkin[b.dataset.checkinKey]===b.dataset.checkinValue));const tl=$('#todayTimeline');tl.innerHTML='';events.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)); if(!events.length){tl.className='timeline empty-state';tl.textContent='Nothing logged yet.';} else {tl.className='timeline';events.forEach(ev=>{const el=document.createElement('div');el.className='timeline-item';el.innerHTML=`<div class="timeline-time">${fmtTime(ev.createdAt)}</div><div><div class="timeline-title">${ev.value}</div><div class="timeline-kind">${ev.type}</div></div><button class="delete-mini" aria-label="Delete">×</button>`;el.querySelector('button').onclick=()=>deleteEvent(ev.id);tl.append(el)});}}
async function refreshHistory(){const [events,dailies]=await Promise.all([getAllEvents(),reqPromise(tx('daily').getAll())]);const map=new Map();for(const ev of events){if(!map.has(ev.day))map.set(ev.day,{events:[],daily:null});map.get(ev.day).events.push(ev)}for(const d of dailies){if(!map.has(d.day))map.set(d.day,{events:[],daily:d});else map.get(d.day).daily=d}const root=$('#historyList');root.innerHTML='';[...map.entries()].sort((a,b)=>b[0].localeCompare(a[0])).forEach(([day,obj])=>{const tags=obj.events.map(e=>e.value);if(obj.daily?.period)tags.push('Period');const taken=Object.entries(obj.daily?.vitamins||{}).filter(([,v])=>v).map(([k])=>k);tags.push(...taken);const card=document.createElement('div');card.className='history-day';card.innerHTML=`<h3>${fmtDate(day)}</h3><div class="history-tags">${tags.length?tags.map(t=>`<span class="mini-tag">${escapeHtml(t)}</span>`).join(''):'<span class="muted">No entries</span>'}</div>`;root.append(card)});if(!map.size)root.innerHTML='<div class="card empty-state">No history yet.</div>';}
async function refreshInsights(){const events=await getAllEvents();const triggers=events.filter(e=>e.type==='trigger');const symptoms=events.filter(e=>e.type==='symptom');$('#insightsSummary').innerHTML=`<p class="eyebrow">YOUR DATA</p><h2>So far</h2><div class="insight-stat"><div class="stat-box"><div class="stat-number">${triggers.length}</div><div class="stat-label">trigger logs</div></div><div class="stat-box"><div class="stat-number">${symptoms.length}</div><div class="stat-label">symptom logs</div></div></div>`;const root=$('#patternCards');root.innerHTML='<p class="eyebrow">PATTERNS</p><h2>Possible associations</h2>';if(triggers.length<3||symptoms.length<3){root.innerHTML+='<p class="muted">Keep logging. Hashi will start showing simple trigger/symptom associations after there is enough data.</p>';return;}const windows=[3,12,24];const groups=[...new Set(triggers.map(t=>t.value))];let cards=[];for(const g of groups){const gs=triggers.filter(t=>t.value===g);for(const w of windows){const counts={};for(const t of gs){const t0=new Date(t.createdAt).getTime();for(const s of symptoms){const dt=(new Date(s.createdAt)-t0)/36e5;if(dt>=0&&dt<=w)counts[s.value]=(counts[s.value]||0)+1;}}const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];if(top&&gs.length>=2){cards.push({score:top[1]/gs.length,g,sym:top[0],hits:top[1],n:gs.length,w});break;}}}cards.sort((a,b)=>b.score-a.score).slice(0,5).forEach(c=>{const div=document.createElement('div');div.className='pattern';div.innerHTML=`<h3>${escapeHtml(c.g)} + ${escapeHtml(c.sym)}</h3><p>${c.sym} was logged within ${c.w} hours after ${c.hits} of ${c.n} ${c.g} entries. This is an association in your journal, not proof that ${c.g} caused the symptom.</p>`;root.append(div)});if(!cards.length)root.innerHTML+='<p class="muted">No clear repeated associations yet.</p>';}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showToast(msg,undo){$('#toastText').textContent=msg;$('#undoBtn').style.display=undo?'block':'none';$('#toast').classList.remove('hidden');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),3000)}
async function undo(){if(lastCreatedId){await deleteEvent(lastCreatedId);lastCreatedId=null;$('#toast').classList.add('hidden')}}
async function clearToday(){if(!confirm('Clear all event logs for today? Vitamins, period, and check-in will stay.'))return;const events=await getDayEvents(todayKey());const s=tx('events','readwrite');for(const e of events)s.delete(e.id);await new Promise((res,rej)=>{s.transaction.oncomplete=res;s.transaction.onerror=()=>rej(s.transaction.error)});await refreshToday();}
function setTab(tab){$('#app').classList.toggle('hidden',tab!=='today');$('#historyView').classList.toggle('hidden',tab!=='history');$('#insightsView').classList.toggle('hidden',tab!=='insights');if(tab==='history')refreshHistory();if(tab==='insights')refreshInsights();window.scrollTo(0,0)}
async function exportData(){const payload={schemaVersion:1,exportedAt:new Date().toISOString(),events:await getAllEvents(),daily:await reqPromise(tx('daily').getAll())};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hashi-backup-${todayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importData(file){const data=JSON.parse(await file.text());if(!Array.isArray(data.events)||!Array.isArray(data.daily))throw new Error('Invalid backup');const etx=db.transaction(['events','daily'],'readwrite');for(const e of data.events)etx.objectStore('events').put(e);for(const d of data.daily)etx.objectStore('daily').put(d);await new Promise((res,rej)=>{etx.oncomplete=res;etx.onerror=()=>rej(etx.error)});showToast('Backup imported',false);await refreshToday();}
async function deleteAll(){if(!confirm('Delete every Hashi entry stored on this device? This cannot be undone unless you exported a backup.'))return;const t=db.transaction(['events','daily'],'readwrite');t.objectStore('events').clear();t.objectStore('daily').clear();await new Promise((res,rej)=>{t.oncomplete=res;t.onerror=()=>rej(t.error)});$('#settingsView').classList.add('hidden');await refreshToday();}
async function init(){await openDB();renderButtons();renderCheckin();const now=new Date();$('#dateLabel').textContent=now.toLocaleDateString([], {weekday:'long',month:'long',day:'numeric'});const standalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true; if(!standalone && localStorage.getItem('hideInstall')!=='1')$('#installBanner').classList.remove('hidden');$('#moreSymptomsBtn').onclick=()=>{$('#moreSymptoms').classList.toggle('hidden');$('#moreSymptomsBtn').textContent=$('#moreSymptoms').classList.contains('hidden')?'More symptoms':'Hide extra symptoms'};$('#takeAllBtn').onclick=takeAll;$('#periodBtn').onclick=togglePeriod;$('#undoBtn').onclick=undo;$('#clearTodayBtn').onclick=clearToday;$$('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#settingsBtn').onclick=()=>$('#settingsView').classList.remove('hidden');$('#closeSettings').onclick=()=>$('#settingsView').classList.add('hidden');$('#exportBtn').onclick=exportData;$('#importInput').onchange=async e=>{try{await importData(e.target.files[0])}catch(err){alert('That backup could not be imported.')}};$('#deleteAllBtn').onclick=deleteAll;$('#dismissInstall').onclick=()=>{localStorage.setItem('hideInstall','1');$('#installBanner').classList.add('hidden')};await refreshToday();if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}
init();
